export enum ProductLabels {
  hs_code = 'Код ТнВЭД',
  article_ved = 'Артикул ВЭД',
  article_erp = 'Артикул ERP',
  trade_mark = 'Торговая марка',
  model = 'Модель/Серия(Тип)',
  modification = 'Модификация',
  product_name = 'Наименование товара',
  quantity_pieces = 'Кол-во штук',
  quantity_places = 'Кол-во мест',
  piece_price = 'Цена за еденицу',
  total_price = 'Общая сумма',
  weight_net = 'Вес нетто',
  weight_gross = 'Вес брутто',
  cbm = 'Объем',
  manufacturer = 'Производитель',
}
